[PROTON] Add missing C++ includes (#3960)
Like #3689, include missing C++ header `algorithm`, otherwise clang 19
throws errors like this:
```
/home/vitalyr/projects/dev/cpp/triton/third_party/proton/csrc/lib/Context/Python.cpp:92:8: error: no member named 'reverse' in namespace 'std'
   92 |   std::reverse(contexts.begin(), contexts.end());
      |   ~~~~~^
1 error generated.
```

Co-authored-by: Your Name <you@example.com>